name: Publish

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Prepare files for upload'
      run: |
        mkdir -p ./upload
        cp ./notblood.pk3 ./upload
        cp -a ./package/common/. ./upload/

    - uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        path: ./upload
        
    - name: Zipping artifacts for release
      run: |
        cd ./upload
        ls -R
        for i in */; do cp *.pk3 "${i%/}"; cp *.txt "${i%/}"; mkdir -p "${i%/}"/autoload; mv "${i%/}"/addons.txt "${i%/}"/autoload; done
        for i in */; do cd "${i%/}"; zip -9 -r "../${i%/}.zip" ./; cd ..; done
    - name: Publish artifacts to release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Build"
        files: |
            ./upload/*.zip
        
    - name: Add download badges
      uses: "irongut/EditRelease@v1.2.0"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        id: "latest"
        body: |
          ## Downloads
          <a href="https://github.com/clipmove/NotBlood/releases/download/latest/notblood-win64.zip" target="_blank"><img src="https://img.shields.io/github/downloads/clipmove/notblood/latest/notblood-win64.zip?color=blue&label=Win64&logo=windows&style=for-the-badge"></a><br><a href="https://github.com/clipmove/NotBlood/releases/download/latest/notblood-win32.zip" target="_blank"><img src="https://img.shields.io/github/downloads/clipmove/notblood/latest/notblood-win32.zip?color=blue&label=Win32&logo=windows&style=for-the-badge"></a><br><a href="https://github.com/clipmove/NotBlood/releases/download/latest/notblood-winxp.zip" target="_blank"><img src="https://img.shields.io/github/downloads/clipmove/notblood/latest/notblood-winxp.zip?color=blue&label=WinXP&logo=windows&style=for-the-badge"></a><br><a href="https://github.com/clipmove/NotBlood/releases/download/latest/notblood-linux-gcc.zip" target="_blank"><img src="https://img.shields.io/github/downloads/clipmove/notblood/latest/notblood-linux-gcc.zip?color=blue&label=Linux-GCC&logo=linux&style=for-the-badge"></a><br><a href="https://github.com/clipmove/NotBlood/releases/download/latest/notblood-linux-clang.zip" target="_blank"><img src="https://img.shields.io/github/downloads/clipmove/notblood/latest/notblood-linux-clang.zip?color=blue&label=Linux-Clang&logo=linux&style=for-the-badge"></a><br><a href="https://github.com/clipmove/NotBlood/releases/download/latest/notblood-macos.zip" target="_blank"><img src="https://img.shields.io/github/downloads/clipmove/notblood/latest/notblood-macos.zip?color=blue&label=MacOs&logo=apple&style=for-the-badge"></a>
